services:
  - type: web
    name: candidate-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_SHEETS_ID
        scope: run
      - key: TELEGRAM_BOT_TOKEN
        scope: run
      - key: TELEGRAM_RECRUITER_CHAT_ID
        scope: run
      - key: GOOGLE_CREDENTIALS_JSON
        scope: run
      - key: CHECK_INTERVAL_HOURS
        value: "1"
